name: another example workflow

on: [pull_request]

jobs:
  
  demonstration:

    runs-on: ubuntu-20.04

    steps:

      - name: Run a one-line script
        run: |
          echo Hello, Tesena Fest!
          echo Hi Aaron, Thanks for awsome workshop!
